config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    collection do
      get 'rank'
      get 'undergraduate'
      get 'course'
    end
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  
  root 'hello#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  mount_uploader :image, ImageUploader
  
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  has_many :comments, dependent: :destroy
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
  
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  
  mount_uploader :image, ImageUploader
  
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(post_id: params[:post_id]) #user_idとpost_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create]
  
  def index
    if params[:search] != nil && params[:search] != ''
        #部分検索かつ複数検索
        search = params[:search]
        @posts = Post.joins(:user).where("body LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%").where(private: false).order(created_at: :desc)
      else
        # プライベート投稿以外のすべての投稿を表示
        @posts = Post.where(private: false).order(created_at: :desc)
    end
  end
  
  def rank
    if params[:search] != nil && params[:search] != ''
        #部分検索かつ複数検索
        search = params[:search]
        @posts = Post.joins(:user).where("body LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%").where(private: false)
      else
        # プライベート投稿以外のすべての投稿を表示
        @posts = Post.where(private: 0)
    end
    
    @rank_posts = Post.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}
    
  end
  
  # 学部プライベート投稿だけを表示
  def undergraduate
    if params[:search] != nil && params[:search] != ''
        #部分検索かつ複数検索
        search = params[:search]
        @posts = Post.joins(:user).where("body LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%").where(private: 1).where(undergraduate: current_user.undergraduate).order(created_at: :desc)
      else
        @posts = Post.where(private: 1, undergraduate: current_user.undergraduate).order(created_at: :desc)
    end
  end
  
  # 学科・コースプライベート投稿だけを表示
  def course
    if params[:search] != nil && params[:search] != ''
        #部分検索かつ複数検索
        search = params[:search]
        @posts = Post.joins(:user).where("body LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%").where(private: 2).where(course: current_user.course).order(created_at: :desc)
      else
        @posts = Post.where(private: 2, course: current_user.course).order(created_at: :desc)
    end
  end

  def new
    @post = Post.new
  end
  
  def create
    post = Post.new(post_params)
    
    post.user_id = current_user.id
    
    if post.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to :action => "show", :id => post.id
    else
      redirect_to :action => "new"
    end
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to action: :index
  end

  private
  def post_params
    params.require(:post).permit(:body, :image, :private, :undergraduate, :course)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show]
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/course.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="posts-container">
  <% if user_signed_in? %>
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <%= button_to 'ユーザー一覧', users_path, method: :get %>
  <% else %>
    <%= link_to "ログイン", new_user_session_path %>
    <%= link_to "新規登録", new_user_registration_path %>
  <% end %>
  
  <!--検索フォーム-->
  <div class="search">
    <h6>メアドか投稿テキストで検索(部分検索可)</h4>
    <%= form_tag({controller:"posts",action:"course"}, method: :get) do %>
      <%= text_field_tag :search %>
      <button type="submit">
        <i class="bi bi-search"></i>
      </button>
    <% end %>
  </div>
  
<h3>学科・コース投稿一覧</h3>
  <%= button_to "全ての投稿を見る", posts_path, method: :get, class: "btn btn-primary" %>
  <% @posts.each do |t| %>
    <div class="card">
      <%= image_tag t.image_url, class: "card-img-top" if t.image? %>
      <div class ="card-body">
        <div class = "card-name">
          <%= image_tag t.user.image_url if t.user.image? %>
          <%= link_to t.user.name, user_path(t.user.id) %>
        </div>
        <div class="left-container">
          <%= t.body %>
        </div>
        <div class="right-container">
          <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="bi bi-heart-fill"></i><%= t.likes.count %>
              <% end %>
            <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="bi bi-heart"></i><%= t.likes.count %>
              <% end %>
            <% end %>
        <% else %>
            <p>いいねの数 = </p><%= t.likes.count %>
        <% end %>
          <div class="btn-group" role="group" aria-label="Basic example">
            <%= link_to "詳細", post_path(t.id), class: "btn btn-secondary" %>
            <% if user_signed_in? && current_user.id == t.user_id %>
              <%= link_to "編集", edit_post_path(t.id), class: "btn btn-secondary" %>
              <%= link_to "削除", post_path(t.id), method: :delete, class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
      <p class="time"><%= t.created_at %></p>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <%= f.label :テキスト %>
  <%= f.text_field :body, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="posts-container">
  <% if user_signed_in? %>
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <%= button_to 'ユーザー一覧', users_path, method: :get %>
  <% else %>
    <%= link_to "ログイン", new_user_session_path %>
    <%= link_to "新規登録", new_user_registration_path %>
  <% end %>
  
  <!--検索フォーム-->
  <div class="search">
    <h6>メアドか投稿テキストで検索(部分検索可)</h4>
    <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
      <%= text_field_tag :search %>
      <button type="submit">
        <i class="bi bi-search"></i>
      </button>
    <% end %>
  </div>
  
<h3>投稿一覧</h3>
  <%= button_to "いいねランキングで表示する", rank_posts_path, method: :get, class: "btn btn-primary" %>
  <%= button_to "学部の投稿を見る", undergraduate_posts_path, method: :get, class: "btn btn-primary" %>
  <%= button_to "学科（コース）の投稿を見る", course_posts_path, method: :get, class: "btn btn-primary" %>
  <% @posts.each do |t| %>
    <div class="card">
      <%= image_tag t.image_url, class: "card-img-top" if t.image? %>
      <div class ="card-body">
        <div class = "card-name">
          <%= image_tag t.user.image_url if t.user.image? %>
          <%= link_to t.user.name, user_path(t.user.id) %>
        </div>
        <div class="left-container">
          <%= t.body %>
        </div>
        <div class="right-container">
          <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="bi bi-heart-fill"></i><%= t.likes.count %>
              <% end %>
            <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="bi bi-heart"></i><%= t.likes.count %>
              <% end %>
            <% end %>
        <% else %>
            <p>いいねの数 = </p><%= t.likes.count %>
        <% end %>
          <div class="btn-group" role="group" aria-label="Basic example">
            <%= link_to "詳細", post_path(t.id), class: "btn btn-secondary" %>
            <% if user_signed_in? && current_user.id == t.user_id %>
              <%= link_to "編集", edit_post_path(t.id), class: "btn btn-secondary" %>
              <%= link_to "削除", post_path(t.id), method: :delete, class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
      <p class="time"><%= t.created_at %></p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
<h3>新規投稿</h3>
  <%= form_for @post do |f| %>
  <div class="field">
    <%= f.label :テキスト %>
    <br>
    <%= f.text_field :body, :size => 30 %>
    <br>
    <div class="field">
      <%= f.label :写真 %>
      <%= f.file_field :image %>
    </div>
    
    <div class="field">
      <%= f.label :プライベート投稿設定 %>
      <%= f.radio_button :private, 0, checked: true %>全員に共有
      <%= f.radio_button :private, 1 %>学部のみで共有
      <%= f.radio_button :private, 2 %>学科（コース）のみで共有
    </div>
    
    <!--投稿者の学部と学科をhiddenで設定-->
    <%= f.hidden_field :undergraduate, :value => current_user.undergraduate %>
    <%= f.hidden_field :course, :value => current_user.course %>
  
    <%= f.submit "投稿する" %>
    <br>

 
  <% end %>
</div>

<%= link_to "一覧に戻る", posts_path %>

app/views/posts/rank.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="posts-container">
  <% if user_signed_in? %>
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <%= button_to 'ユーザー一覧', users_path, method: :get %>
  <% else %>
    <%= link_to "ログイン", new_user_session_path %>
    <%= link_to "新規登録", new_user_registration_path %>
  <% end %>
  
  <!--検索フォーム-->
  <div class="search">
    <h6>メアドか投稿テキストで検索(部分検索可)</h4>
    <%= form_tag({controller:"posts",action:"rank"}, method: :get) do %>
      <%= text_field_tag :search %>
      <button type="submit">
        <i class="bi bi-search"></i>
      </button>
    <% end %>
  </div>
  
<h3>いいね順 投稿一覧</h3>
  <%= button_to "投稿順に表示する", posts_path, method: :get, class: "btn btn-primary" %>
  <!--いいねランキング-->
  <% @rank_posts.each do |t| %>
    <div class="card">
      <%= image_tag t.image_url, class: "card-img-top" if t.image? %>
      <div class ="card-body">
        <div class = "card-name">
          <%= image_tag t.user.image_url if t.user.image? %>
          <%= link_to t.user.name, user_path(t.user.id) %>
        </div>
        <div class="left-container">
          <%= t.body %>
        </div>
        <div class="right-container">
          <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="bi bi-heart-fill"></i><%= t.likes.count %>
              <% end %>
            <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="bi bi-heart"></i><%= t.likes.count %>
              <% end %>
            <% end %>
        <% else %>
            <p>いいねの数 = </p><%= t.likes.count %>
        <% end %>
          <div class="btn-group" role="group" aria-label="Basic example">
            <%= link_to "詳細", post_path(t.id), class: "btn btn-secondary" %>
            <% if user_signed_in? && current_user.id == t.user_id %>
              <%= link_to "編集", edit_post_path(t.id), class: "btn btn-secondary" %>
              <%= link_to "削除", post_path(t.id), method: :delete, class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
      <p class="time"><%= t.created_at %></p>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<h2>投稿詳細</h2>

<div class="post">
  <p><%= @post.user.email %></p>
  <%= image_tag @post.image_url, size: "250x200" if @post.image? %>
  <h3><%= @post.body %></h3>
  <p><%= @post.created_at %></p>
  
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
          <%= link_to post_like_path(@post), method: :delete do %>
             <p>いいねを取り消す</p><%= @post.likes.count %>
          <% end %>
      <% else %>
          <%= link_to post_likes_path(@post), method: :post do %>
             <p>いいね</p><%= @post.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <p>いいねの数 = </p><%= @post.likes.count %>
  <% end %>

</div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "編集する", edit_post_path(@post.id) %>
<%= link_to "投稿一覧に戻る", posts_path %>

app/views/posts/undergraduate.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="posts-container">
  <% if user_signed_in? %>
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <%= button_to 'ユーザー一覧', users_path, method: :get %>
  <% else %>
    <%= link_to "ログイン", new_user_session_path %>
    <%= link_to "新規登録", new_user_registration_path %>
  <% end %>
  
  <!--検索フォーム-->
  <div class="search">
    <h6>メアドか投稿テキストで検索(部分検索可)</h4>
    <%= form_tag({controller:"posts",action:"undergraduate"}, method: :get) do %>
      <%= text_field_tag :search %>
      <button type="submit">
        <i class="bi bi-search"></i>
      </button>
    <% end %>
  </div>
  
<h3>学部投稿一覧</h3>
  <%= button_to "全ての投稿を見る", posts_path, method: :get, class: "btn btn-primary" %>
  <% @posts.each do |t| %>
    <div class="card">
      <%= image_tag t.image_url, class: "card-img-top" if t.image? %>
      <div class ="card-body">
        <div class = "card-name">
          <%= image_tag t.user.image_url if t.user.image? %>
          <%= link_to t.user.name, user_path(t.user.id) %>
        </div>
        <div class="left-container">
          <%= t.body %>
        </div>
        <div class="right-container">
          <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="bi bi-heart-fill"></i><%= t.likes.count %>
              <% end %>
            <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="bi bi-heart"></i><%= t.likes.count %>
              <% end %>
            <% end %>
        <% else %>
            <p>いいねの数 = </p><%= t.likes.count %>
        <% end %>
          <div class="btn-group" role="group" aria-label="Basic example">
            <%= link_to "詳細", post_path(t.id), class: "btn btn-secondary" %>
            <% if user_signed_in? && current_user.id == t.user_id %>
              <%= link_to "編集", edit_post_path(t.id), class: "btn btn-secondary" %>
              <%= link_to "削除", post_path(t.id), method: :delete, class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
      <p class="time"><%= t.created_at %></p>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<h1>DM</h1>

<h4>参加者</h4>
<% @entries.each do |e| %>
  <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.email%>さん</a></strong></h5>
<% end %>

<hr>
<% if @messages.present? %>
  <% @messages.each do |m| %>
    <strong><%= m.content %></strong>
    <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.email %>さん</a></strong></small>
    <hr>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>

<%= form_for @message do |f| %>
  <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <br>
  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% if user_signed_in? %>
  <% @users.each do |u| %>
  <p><a href="/users/<%= u.id %>"><%= u.email %></a></p>
  <hr>
  <% end %>
  <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "ユーザー登録", new_user_registration_path %>
  <br>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'user_show', :media => "all" %>
<div class="user_show">
  
<h1><%= @user.name %>のページ</h1>
<%= image_tag @user.image_url, size: "250x200" if @user.image? %>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>学部 : <%= @user.undergraduate %></p>
<p>学科またはコース : <%= @user.course %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path, class: "btn btn-primary" %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
  <br>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_posts.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
  <br>
<% end %>
<!-- ここまで-->

<% if @user.id == current_user.id %>

<% else %>
  <% if @isRoom == true %>
    <p><a href="/rooms/<%= @roomId %>">チャットへ</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <%= f.submit "チャットを始める" %>
    <% end %>
  <% end %>
<% end %>

<%= link_to "投稿一覧に戻る", posts_path, class: "btn btn-primary" %>
</div>