config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    collection do
      get 'rank'
      get 'undergraduate'
      get 'course'
    end
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  
  root 'hello#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  mount_uploader :image, ImageUploader
  
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  has_many :comments, dependent: :destroy
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
  
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  
  mount_uploader :image, ImageUploader
  
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(post_id: params[:post_id]) #user_idとpost_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create]
  
  def index
    if params[:search] != nil && params[:search] != ''
        #部分検索かつ複数検索
        search = params[:search]
        @posts = Post.joins(:user).where("body LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%").where(private: false).order(created_at: :desc)
      else
        # プライベート投稿以外のすべての投稿を表示
        @posts = Post.where(private: false).order(created_at: :desc)
    end
  end
  
  def rank
    if params[:search] != nil && params[:search] != ''
        #部分検索かつ複数検索
        search = params[:search]
        @posts = Post.joins(:user).where("body LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%").where(private: false)
      else
        # プライベート投稿以外のすべての投稿を表示
        @posts = Post.where(private: 0)
    end
    
    @rank_posts = Post.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}
    
  end
  
  # 学部プライベート投稿だけを表示
  def undergraduate
    if params[:search] != nil && params[:search] != ''
        #部分検索かつ複数検索
        search = params[:search]
        @posts = Post.joins(:user).where("body LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%").where(private: 1).where(undergraduate: current_user.undergraduate).order(created_at: :desc)
      else
        @posts = Post.where(private: 1, undergraduate: current_user.undergraduate).order(created_at: :desc)
    end
  end
  
  # 学科・コースプライベート投稿だけを表示
  def course
    if params[:search] != nil && params[:search] != ''
        #部分検索かつ複数検索
        search = params[:search]
        @posts = Post.joins(:user).where("body LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%").where(private: 2).where(course: current_user.course).order(created_at: :desc)
      else
        @posts = Post.where(private: 2, course: current_user.course).order(created_at: :desc)
    end
  end

  def new
    @post = Post.new
  end
  
  def create
    post = Post.new(post_params)
    
    post.user_id = current_user.id
    
    if post.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to :action => "show", :id => post.id
    else
      redirect_to :action => "new"
    end
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to action: :index
  end

  private
  def post_params
    params.require(:post).permit(:body, :image, :private, :undergraduate, :course)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MYCAP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  </head>

  <body>
    <header>
      <h1><%= link_to "MYCAP", root_path %></h1>
      <div class="header-list">
      <ul>
        <%= link_to root_path, class: "icon", method: :get do %>
          <i class="bi-header bi-house"></i>
        <% end %>
       
        <%= link_to new_post_path, method: :get do %>
          <i class="bi-header bi-pencil-square"></i>
        <% end %>
        
        <% if user_signed_in? %>
          <%= link_to user_path(current_user.id), method: :get do %>
            <i class="bi-header bi-person"></i>
          <% end %>
        <% end %>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p>©2022 トクメモプロジェクト All Rights Reserved.</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>